const users = [
    {
        trackImg: "img/icon/sprite.svg#icon-note",
        trackName: "Gulit",
        autorName: "Nerzo",
        albumName: "Welcome Reality",
        trackTime: "4:44",
    },
    {
        trackImg: "img/icon/sprite.svg#icon-note",
        trackName: "Elektro",
        autorName: "Dynoro, Outwork, Mr. Gee",
        albumName: "Elektro",
        trackTime: "2:22",
    },
    {
        trackImg: "img/icon/sprite.svg#icon-note",
        trackName: "I’m Fire",
        autorName: "Ali Bakgor",
        albumName: "I’m Fire",
        trackTime: "2:22",
    },
    {
        trackImg: "img/icon/sprite.svg#icon-note",
        trackName: "Non Stop",
        autorName: "Стоункат, Psychopath",
        albumName: "Non Stop",
        description: "(Remix)",
        trackTime: "4:12",
    },
    {
        trackImg: "img/icon/sprite.svg#icon-note",
        trackName: "Run Run",
        autorName: "Jaded, Will Clarke, AR/CO",
        albumName: "Run Run",
        description: "(feat. AR/CO)",
        trackTime: "2:54",
    },
    {
        trackImg: "img/icon/sprite.svg#icon-note",
        trackName: "Eyes on Fire",
        autorName: "Blue Foundation, Zeds Dead",
        albumName: "Eyes on Fire",
        description: "(Zeds Dead Remix)",
        trackTime: "5:20",
    },
    {
        trackImg: "img/icon/sprite.svg#icon-note",
        trackName: "Mucho Bien",
        autorName: "HYBIT, Mr. Black, Offer Nissim, Hi Profile",
        albumName: "Mucho Bien",
        description: "(Hi Profile Remix)",
        trackTime: "3:41",
    },
    {
        trackImg: "img/icon/sprite.svg#icon-note",
        trackName: "Knives n Cherries",
        autorName: "minthaze",
        albumName: "Captivating",
        description: "",
        trackTime: "1:48",
    },
    {
        trackImg: "img/icon/sprite.svg#icon-note",
        trackName: "Knives n Cherries",
        autorName: "minthaze",
        albumName: "Captivating",
        description: "",
        trackTime: "1:48",
    },
    {
        trackImg: "img/icon/sprite.svg#icon-note",
        trackName: "Knives n Cherries",
        autorName: "minthaze",
        albumName: "Captivating",
        description: "",
        trackTime: "1:48",
    },
    {
        trackImg: "img/icon/sprite.svg#icon-note",
        trackName: "Knives n Cherries",
        autorName: "minthaze",
        albumName: "Captivating",
        description: "",
        trackTime: "1:48",
    },
    {
        trackImg: "img/icon/sprite.svg#icon-note",
        trackName: "Knives n Cherries",
        autorName: "minthaze",
        albumName: "Captivating",
        description: "",
        trackTime: "1:48",
    },
    {
        trackImg: "img/icon/sprite.svg#icon-note",
        trackName: "Knives n Cherries",
        autorName: "minthaze",
        albumName: "Captivating",
        description: "",
        trackTime: "1:48",
    },
    {
        trackImg: "img/icon/sprite.svg#icon-note",
        trackName: "Knives n Cherries",
        autorName: "minthaze",
        albumName: "Captivating",
        description: "",
        trackTime: "1:48",
    },
   
]
export default users